### ISSUE TITLE
Some of blocks content inside file is found to be zero. Looks like "persist" related issue.

### ISSUE THREAD

**Issue by jjz** [copernet/copernicus#77] opened 2018-09-23 04:20 UTC

**Comment by detailyang** [comment] 2018-09-25 00:53
Does any way to reproduce it? 
Maybe it's fixed at [https://github.com/copernet/copernicus/pull/45](https://github.com/copernet/copernicus/pull/45).  My [toolkit](https://github.com/detailyang/coper-toolkit) had tried to analyze some block files (blk0000.dat、blk00001.dat....) in latest version, It looks like no zero padding.

**Comment by whunmr** [comment] 2018-11-25 16:10
thanks for help guys,
haven't seen related bugs during last month,  I'd like to close this issue now, 
and will reopen this issue when we found related issues or steps to reproduce this one.

**Closed by whunmr** 2018-11-25 16:10 UTC
